import Navbar from './components/Navbar';
import Home from './components/Home';
import Store from './components/Store';
import Learn from './components/Learn';
import About from './components/About';
import Contact from './components/Contact';
import Login from './components/Login';
import SignUp from './components/SignUp';
import Cart from './components/Cart';
